version: "3.9"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    networks:
      - neohub-net

networks:
  neohub-net:
    external: true
    name: neohub_neohub-net